# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f899e6461e8f0bac4d8d1ac10eaa74c7a496f10fab3b3530fd0e90d130af74ed064eaa3a639fc3d666f7c49f0fa965218ccd1fedc93c2663837ee3f4223eef

test:
  secret_key_base: 418b579ef8fb0af597c11a2381298af4162b70d8dceb71eba4a38aeebc72609d9902c46cae684d759f5cedba955663a6e2bcd2471e28a0249ee186067ce4c2cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
